// NÃO PODEMOS CRIAR CONSTANTE COM PALAVRAS RESERVADAS EX. let console ou let if 
// CONSTANTE PRECISAM TER NOMES SIGNIFICATIVOS 
// NÃO COMECAR O NOME DE UMA CONSTANTE COM NÚMERO 
// OS NOMES DAS CONSTANTES NÃO PODEM CONTER ESPAÇOS OU TRAÇOS
// UTILIZAMOS CAMELCASE EX. nomeCompleto
// AS CONSTANTES SÃO CASE-SENSITIVE( LETRAS MAIUSCULAS E MINUSCULAS FAZER DIFERENÇA
// NÃO PODE MODIFICAR O VALOR DE UMA CONSTANTE 
// NÃO UTILIZE VAR , UTILIZE CONST

const nome = 'João';
console.log(nome);

const primeiroNumero = 10;
const segunNumero = 5;
const resultado = primeiroNumero * segunNumero;

console.log(typeof(primeiroNumero));
